name: Bump Homebrew Formulae

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Bump formula
        uses: Homebrew/actions/bump-packages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formulae: gdvm
