name: Bump Homebrew Formulae

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Bump formula
        uses: Homebrew/actions/bump-packages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: patricktcoakley/homebrew-formulae
          create_pull_request: true
